### PR TITLE
WIP: OpenAI support

### PR DESCRIPTION
**Pull request by theoxo**
@benlipkin as promised, here's a little MVP for OpenAI support.

Basically:
- OpenAI API keys are given by passing the names of the environment variables containing them. This is to keep things log-safe and easy to manage.
- If at least one API key has been given, `runner.py` tries to find the given model on OpenAI. HF is only used if this fails.
- Evaluator is now an abstract class. The old Evaluator is now called HFEvaluator and implements Evaluator. There is a new Evaluator called OAIEvaluator. The evaluation method is in both cases inherited from Evaluator.

Obvious flaws/TODOs:
- I haven't added any pre-processing of the prompt or post-processing of the generations etc
- Some stuff is probably not in the right place. Happy to talk about at what point we should start splitting OpenAI-specific stuff into its own file.
- Have only tried this super quickly with `python3 runner.py --model "text-ada-001" --limit 1 --openai_api_env_keys "OPENAI_1" "OPENAI_2" --tasks "folio-baseline-2shot" --allow_code_execution`, no thorough testing done.

### CODE REVIEW

**Comment by theoxo** [comment]
re: "bouncing between API keys when hitting rate limits": right now, when all keys have been rate limited you'll spin on the recursive call. Would probably be better to have some way of "timing out" a given token, and once all tokens have been timed out you sleep until one of them reawakens. That's getting into some serious synchro shit though - maybe there's an easier way to get the same effect that I haven't thought of yet

**Comment by benlipkin** [comment]
@theoxo this is great! Made a few add-ons.

1) I added a few more errors I usually cover as you noted in your todo, and pinned an openai version in `requirements.txt` in case breaking changes are introduced over the duration of this project.
2) I added task-defined stopwords to the API request to mimic the same generation control as HF completion.
3) I took a stab at accumulating the times at which keys have timed out and placing them back into the accessible pool dynamically then doing a full wait and reset once all keys are exhausted. It's not perfect and I haven't really tested it yet, but seems to be along the right direction. Feel free to play around with this more if you have better ideas.
4) I incorporated the `postprocess_generation` workflow around the openai API completions and added a new kwarg to handle the different output formats, e.g., HF returns prompt+completion+stopword and needs to be stripped out vs OAI just returns completion.

Let me know how these look on your end.

**Comment by minimario** [comment]
It may also be great to implement some level of caching to save money (if you query the same API multiple times with the same text and temperature = 0, then don't invoke the API, just fetch the result from the cache)

**Comment by benlipkin** [comment]
Thanks @minimario good idea. Just added thread- and process-safe persistent cache using `diskcache`. Tried to enumerate set of relevant arguments that need to be held constant in order to initiate a hit [here](https://github.com/benlipkin/L3M/pull/1/files#diff-c5f6d874d90041488e0321706da303d6d6a57aa1415b84f1dcbb04103b88e5c8R134). Let me know if I missed anything.

Otherwise, the rest of this lg2m. Can merge once you're both satisfied as well.

**Review by benlipkin — APPROVED** [review]

**Pull request merged**
